# Generated by Django 4.1.4 on 2023-01-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_armwrestler_patronymic'),
    ]

    operations = [
        migrations.AddField(
            model_name='armwrestler',
            name='trainers',
            field=models.ManyToManyField(to='main.trainer'),
        ),
    ]
