# Generated by Django 4.1.4 on 2023-01-06 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_armwrestler_trainers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='lubovnica',
        ),
    ]
