# Generated by Django 4.1.4 on 2023-01-15 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_trainer_lubovnica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armwrestler',
            name='trainers',
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_category', models.CharField(max_length=4)),
                ('place', models.IntegerField()),
                ('sportsmen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.armwrestler')),
            ],
        ),
    ]
