# Generated by Django 4.1.4 on 2023-01-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_trainer_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='students',
            field=models.ManyToManyField(to='main.armwrestler'),
        ),
    ]
